apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: monitoring
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://github.com/Gurjit86/argo-cd-example.git
    path: grafana
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
